user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log notice;
pid /run/nginx.pid;

include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    keepalive_timeout   65;
    types_hash_max_size 4096;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    upstream php-fpm {
        server 127.0.0.1:9000;
    }

    server {
        listen      80 default_server;
        listen      [::]:80 default_server;
        server_name _;
        root        /opt/pivx-name-indexer;
        access_log  /var/log/nginx/pivx-name-indexer.loc.access.log;
        error_log   /var/log/nginx/pivx-name-indexer.loc.error.log error;

        fastcgi_intercept_errors on;
        recursive_error_pages on;

        location ~ ^/v.*$ {
            if ($is_args) {
                return 404;
            }

            if ($uri ~ '^/.+/+$') {
                return 404;
            }

            fastcgi_pass   php-fpm;
            fastcgi_param  SCRIPT_FILENAME  $document_root/api.php;
            include        fastcgi_params;
            fastcgi_param PHP_VALUE open_basedir="/opt/pivx-name-indexer:/tmp:/var/log/indexer";
        }
    }
}
