POST https://indexer.pivxname.loc/v1.0/resolve/reverse/ps1a5dvcrw8k49tcmmsmfh2d5cthhamfrxue4h3ervww2z625qwyarcflpznaxlalwk7trkyxas4ln
#POST https://indexer.pivxname.loc/v1.0/resolve/owner/3757ee1a8b3f10353ca6edd47b66920392b02e323dca3f3edddb5de142079a53
#POST https://indexer.pivxname.loc/v1.0/resolve/alexxiy.secure
Content-Type: application/json

{
  "extended": true,
  "with_checkpoint": true
}
